print("Welcome to the tip Calculator!")
bill = float(input("What was the total bill?"))
tip = int(input("How much tip would you like to give? 10,12, or 15 ?"))
poeples = int(input("How many people to split the bill?"))
print("Each person should pay: $" + str(round((bill*(tip+100)/100/poeples),2)))
